### ISSUE TITLE
Enable dynamic loading of `AccountResourceProvider`

### ISSUE THREAD

**Issue by garronej** [p2-inc/keycloak-account-v1#7]
Hello @xgp!

Currently, Keycloakify generates two different .jar files: one for use with Keycloak versions prior to 23, and another for Keycloak 23 and up. It would be greatly beneficial if Keycloakify users could ship a single .jar that works across all versions.

Do you think there is a way to dynamically load elements related to AccountResourceProvider?

Our main goal is to prevent Keycloak from crashing at startup on versions prior to 23.

I'm not sure if this is feasible, but I would highly appreciate your insights on this matter.

**Comment by xgp** [comment]
@garronej There isn't really a way to do this, given that all of this gets loaded by the Java service loader mechanism at startup. And, since the class isn't present in earlier versions of Keycloak, that will always yield a `ClassNotFoundException` when it is loaded. There might be some way to dynamically load it from a generic `Provider`, but that's beyond my understanding of how providers get loaded in Keycloak, and is probably not a stable way to do it in the long term.

**Comment by garronej** [comment]
Okay, makes sense!  
Well, It's no big deal. We'll just continue shipping two jars.

**Comment by garronej** [comment]
Thank you for checking it out!
